import './globals.css'

export const metadata = {
  title: 'My Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       <link rel="stylesheet" href="/compiled-tailwind.css" />
      <body>{children}</body>
    </html>
  )
}
